services:
  app:
    build: .
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "bundle install &&
       rm -f tmp/pids/server.pid &&
       rake db:drop || true &&
       rake db:create &&
       rake db:migrate &&
       rake db:seed &&
       rails s -p 3002 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:expertiza@db:3306/reimplementation?
      CACHE_STORE: redis://redis:6380/0
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: expertiza
      MYSQL_ROOT_PASSWORD: expertiza
    ports:
      - "3307:3306"
    volumes:
      - expertiza-mysql:/var/lib/mysql2/data
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6380:6380"
    volumes:
      - expertiza-redis:/var/lib/redis/data

volumes:
  expertiza-mysql:
  expertiza-redis:
